### ISSUE TITLE
Syntax error parsers.py

### ISSUE THREAD

**Issue by job** [stkonst/PolicyParser#1]
I might be doing something wrong installing this on MacOSX, but it appears there is a syntax error somewhere: in `parsers.py` `except et.ParseError, et.TypeError:`

```
22:PolicyParser job$ virtualenv .venv
Using base prefix '/usr/local/Cellar/python3/3.5.1/Frameworks/Python.framework/Versions/3.5'
New python executable in /Users/job/source/PolicyParser/.venv/bin/python3.5
Also creating executable in /Users/job/source/PolicyParser/.venv/bin/python
Installing setuptools, pip, wheel...done.

22:PolicyParser job$ source .venv/bin/activate
(.venv) 22:PolicyParser job$ pip install -r re
Could not open requirements file: [Errno 2] No such file or directory: 're'
(.venv) 22:PolicyParser job$ pip install -r requirements.txt
Collecting gevent==1.1.1 (from -r requirements.txt (line 1))
  Downloading gevent-1.1.1-cp35-cp35m-macosx_10_6_intel.whl (473kB)
    100% |████████████████████████████████| 481kB 1.4MB/s
Collecting requests==2.9.1 (from -r requirements.txt (line 2))
  Downloading requests-2.9.1-py2.py3-none-any.whl (501kB)
    100% |████████████████████████████████| 501kB 1.5MB/s
Collecting xxhash==0.5.0 (from -r requirements.txt (line 3))
  Downloading xxhash-0.5.0.zip
Collecting greenlet>=0.4.9 (from gevent==1.1.1->-r requirements.txt (line 1))
  Downloading greenlet-0.4.9.zip (78kB)
    100% |████████████████████████████████| 81kB 2.2MB/s
Building wheels for collected packages: xxhash, greenlet
  Running setup.py bdist_wheel for xxhash ... done
  Stored in directory: /Users/job/Library/Caches/pip/wheels/bd/a8/37/2823cd312f9b5a107afd5b66aabf9607710a206d3e4d2ae023
  Running setup.py bdist_wheel for greenlet ... done
  Stored in directory: /Users/job/Library/Caches/pip/wheels/54/85/ff/b9794e7f8dd8b845a7712885d2f7e8513d0e8fc1c91e01bc6f
Successfully built xxhash greenlet
Installing collected packages: greenlet, gevent, requests, xxhash
Successfully installed gevent-1.1.1 greenlet-0.4.9 requests-2.9.1 xxhash-0.5.0

(.venv) 22:PolicyParser job$ python librpsl.py -b AS1234,AS5678 -o as3333.xml AS3333
Traceback (most recent call last):
  File "librpsl.py", line 5, in <module>
    import parsers
  File "/Users/job/source/PolicyParser/parsers.py", line 66
    except et.ParseError, et.TypeError:
                        ^
SyntaxError: invalid syntax
(.venv) 22:PolicyParser job$
```

**Comment by job** [comment]
Error is probably due to my environment:

```
(.venv) 22:PolicyParser job$ pip freeze
gevent==1.1.1
greenlet==0.4.9
requests==2.9.1
xxhash==0.5.0
(.venv) 22:PolicyParser job$ python -V
Python 3.5.1
(.venv) 22:PolicyParser job$
```
